name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd helloworld
          npm install
          
      - name: Run Tests
        run: |
          cd helloworld
          npm test
          
      - name: Run Security Audit
        run: |
          cd helloworld
          npm audit --audit-level=high 
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
           app-name: azure400project-manan3112
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
           package: ./helloworld
